[ABW-3911] Discover Radix dApps home card
radixdlt/sargon pull request #257
Opened 2024-11-08 11:45 UTC by danvleju-rdx

Jira ticket: [ABW-3911](https://radixdlt.atlassian.net/browse/ABW-3911)

- Adds a new home carousel card for new users that redirects to the Radix Ecosystem

2024-11-08 12:08 UTC, matiasbzurovski approved these changes
LGTM, just one product question asked in Slack to confirm this should also be shown when `HomeCard::Dapp` is also present

2024-11-08 12:10 UTC, GhenadieVP approved these changes

2024-11-08 12:40 UTC, CyonAlexRDX requested changes
Best derive Ord :)

2024-11-11 12:21 UTC, CyonAlexRDX approved these changes
LGTM

2024-11-11 12:25 UTC, merged